# You can use this to store API keys, mail server settings,
# or any other kind of configuration data that your application needs.
# In order to keep your production settings secret, store the production
# copy of this file on your server under shared/config/config.yml and copy
# it on deployment with this Capistrano task:#

# task :copy_config_files do
#   filename = "config/config.yml"
#   run "cp #{shared_path}/#{filename} #{release_path}/#{filename}"
# end
# after "deploy:update_code", :copy_config_files

development: &non_production_settings
  encryption_key: e0151c8eb72bde809499a2805a17c33e44fc99a1b71bc0f20fdf306b2e33f4b5384fcb8e323f91f7fa360b0d06b000e1cdd13935a8d930eb6afc6efe6f6a3316
  mailer:
    server: mail.example.com
    username: someLOGIN
    password: s0meth1ngs3cr3t
  paypal:
    ip:         192.168.0.1
    login:      someLOGIN.yahoo.com
    password:   somePASSWORD
    signature:  someSIGNATURE
  authnet:
    login:      someLOGIN
    password:   somePASSWORD
  braintree:
    merchant_id: 'v4fv38hhvmrg369p'
    public_key: '52bb84mg4sqgpcnx'
    private_key: 'eac177db25b5c60d49345050ffc8d7bd'
  vat: false

test:
  <<: *non_production_settings

production:
  encryption_key: e0151c8eb72bde809499a2805a17c33e44fc99a1b71bc0f20fdf306b2e33f4b5384fcb8e323f91f7fa360b0d06b000e1cdd13935a8d930eb6afc6efe6f6a3316
  mailer:
    server: mail.example.com
    username: someLOGIN
    password: somePASSOWRD
  paypal:
    ip:         192.168.0.1
    login:      someLOGIN.yahoo.com
    password:   somePASSWORD
    signature:  someSIGNATURE
  authnet:
    login:      someLOGIN
    password:   somePASSWORD
  braintree:
    merchant_id: 'v4fv38hhvmrg369p'
    public_key: '52bb84mg4sqgpcnx'
    private_key: 'eac177db25b5c60d49345050ffc8d7bd'
  vat: false